# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ cicd_workflow ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v2

      # Install required dependecies
      - name: Install Dependencies
        run: npm install

      # Runs Jest tests, separately in back- and frontend for convenience
      - name: Run the Jest tests
        run: cd api && npm run test -- --coverage && cd ../front && npm run test -- --watchAll=false --verbose --coverage
      
      # Sends coverage report to Codecov
      - name: Send coverage to Codecov
        uses: codecov/codecov-action@v2

      # Linting
      - name: lint api
        run: cd api && npm run lint
      
      - name: lint front
        run: cd front && npm run lint
      

      # Send slack message to ci/cd channel
      - name: Notify on slack
        if: ${{ github.event_name == 'pull_request' }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: author,pullRequest,commit
          text: 'Code review waiting'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
